repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: check-added-large-files
    - id: check-merge-conflict
    - id: check-ast
    - id: check-toml
    - id: check-yaml
      args: [--unsafe]  # Required due to custom constructors (e.g. !ENV)
    - id: end-of-file-fixer
    - id: trailing-whitespace
      args: [--markdown-linebreak-ext=md]
- repo: https://github.com/psf/black
  rev: 23.7.0
  hooks:
    - id: black
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.0.285
  hooks:
    - id: ruff
- repo: https://github.com/python-poetry/poetry
  rev: 1.5.0
  hooks:
    - id: poetry-check
    - id: poetry-lock

# Custom hooks
- repo: local
  hooks:
    - id: poetry-up
      name: poetry-up
      entry: poetry
      args: ["up"]
      language: system
      pass_filenames: false
      serial: true
    - id: mypy
      name: mypy
      entry: mypy
      args: ["."]
      language: system
      pass_filenames: false
      serial: true
