services:
  bot-base: &bot-base
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile

  bot-prod:
    <<: *bot-base
    container_name: discord-bot
    mem_limit: 2048m
    cpus: 6

  bot-dev:
    <<: *bot-base
    container_name: discord-bot-dev
    mem_limit: 512m
    cpus: 2
    build:
      args:
        - build=with dev
    volumes:
      - ./bot/exts:/app/bot/exts
    x-develop:
      watch:
        - action: sync
          path: ./bot
          target: /app/bot
        - action: rebuild
          path: poetry.lock
