services:
  bot-prod:
    container_name: discord-bot
    restart: unless-stopped
    build:
      context: .
      target: prod-build
      dockerfile: Dockerfile
    tty: true

  bot-dev:
    container_name: discord-bot-dev
    restart: unless-stopped
    build:
      context: .
      target: dev-build
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./bot:/app/bot
      - ./.env:/app/.env
