services:
  bot-base: &bot-base
    restart: unless-stopped
    tty: true
    entrypoint: poetry
    build:
      context: .
      dockerfile: Dockerfile

  bot-prod:
    <<: *bot-base
    container_name: discord-bot
    build:
      target: prod-build
    mem_limit: 2048m
    cpus: 2
    command: run python -m bot -OO

  bot-dev:
    <<: *bot-base
    container_name: discord-bot-dev
    build:
      target: dev-build
    volumes:
      - ./bot/exts:/app/devbot/bot/exts
    mem_limit: 512m
    cpus: 1
    command: run python -m bot
