services:
  bot-prod:
    container_name: discord-bot
    restart: unless-stopped
    build:
      context: .
      target: prod-build
      dockerfile: Dockerfile
    tty: true
    mem_limit: 512m
    cpus: 0.25
    environment:
      - TOKEN=${TOKEN}

  bot-dev:
    container_name: discord-bot-dev
    restart: unless-stopped
    build:
      context: .
      target: dev-build
      dockerfile: Dockerfile
    tty: true
    volumes:
      - .:/app/bot
    mem_limit: 512m
    cpus: 0.25
