name: netcup-docker-deployment

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy project
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/discord-py-template/ || git clone https://github.com/Pandabweer/discord-py-template/
            git fetch origin bot-preview
            git reset --hard FETCH_HEAD
            git clean -df --exclude secrets
            rm -rf .env
            echo -e "TOKEN=${{ secrets.DISCORD_TOKEN }}" >> .env
            docker compose build --no-cache bot-prod
            docker compose up bot-prod --detach --no-build
            docker system prune -af
