name: lint-type-format

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  validate-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: make build-dev

      - name: Run all check inside Docker container
        run: |
          cd bot && \
          make format-check lint-check && \
          docker compose run --rm bot-dev run --quiet mypy . --cache-dir=/dev/null

      - name: Cleanup
        run: docker system prune -a -f
